### ISSUE TITLE
Add DeepCopy capabilities for DynamicObj

### ISSUE THREAD

**Issue by kMutagene** [CSBiology/DynamicObj#35]
Update: renamed this issue so we can focus on the combine rework in another one: #43 

Both _should_ do the same (or there needs to be a `_.combine` instance method), and i think they should be adapted to not mutate any of the 2 objects but rather return a new object.

**Comment by kMutagene** [comment]
Additionally, `CopyDynamicPropertiesTo` should not fail if `overwrite` is set to false. The expected behavior is that on `overWrite = false`, new properties are added to the target, but existing ones are kept as-is.

**Comment by kMutagene** [comment]
This has been a gigantic rabbit hole, and the solution is not very satisfiying, but we at least have some Deep copy capabilities in https://github.com/CSBiology/DynamicObj/pull/42 . It is i think impossible to return a completely copied result though, as we do not have enough knowledge about boxed dynamic props to deep copy any type/class (and there might be ones that cannot be deep copied anyways). I have settled on a "good enough" approach for now.

**Comment by HLWeil** [comment]
So typed objects without a "Copy" method will result in a "DynamicObject" with the same fields?

**Comment by kMutagene** [comment]
> So typed objects without a "Copy" method will result in a "DynamicObject" with the same fields?

Yes but Note that this is a draft PR. I think there is a point to be made that static properties should be copied as well. That way, we can "recover" the derived class if needed. 

I think there is no other way for this method. This is the 'try maximum nested deep copy' method. I think as long as this is well documented everything is fine.

**Comment by HLWeil** [comment]
Oh, so currently only the dynamic properties are copied? Shouldn't it be a simple addition to copy the static fields too? E.g. decided by an optional boolean parameter?

Yes, there is no secure way to deep copy classes, even via Reflection. You can never be sure how the constructor is meant to be used.

**Comment by kMutagene** [comment]
Note that this will not be closed via #42, combine still needs work afterwards

**Comment by kMutagene** [comment]
Closed via #42
