### ISSUE TITLE
Combine IDOs

### ISSUE THREAD

**Issue by WhiteBlackGoose** [CSBiology/DynamicObj#7]
What API should be there?

**Comment by HLWeil** [comment]
duplicate of #35? @kMutagene

**Comment by kMutagene** [comment]
@HLWeil this is concerning the immutable dynamic objects, which we have moved to [DynamicObj.Immutable](https://github.com/CSBiology/DynamicObj/tree/main/src/DynamicObj.Immutable). I there was initial interest from @WhiteBlackGoose on working on that, but i think we can close this - anyone feel free to reopen if needed.
