### ISSUE TITLE
Unify DO/IDO APIs

### ISSUE THREAD

**Issue by kMutagene** [CSBiology/DynamicObj#9]
Ideally, both APIs should provide the exact same functionality. While the mutable operations on DO have no equivalents, here are some things we should do IMO:

- [ ] Add pipeable versions for add/remove etc, and the new set (e.g. ++, +?) of operators to DO 
- [ ] Remove the `DynObj` namespace (it is confusing), make all functions contained there static members of `DynamicObj`

**Comment by HLWeil** [comment]
Can be closed if it's not being worked on?

**Comment by kMutagene** [comment]
Yes, we even discussed why 

>  Remove the DynObj namespace (it is confusing), make all functions contained there static members of DynamicObj

Is not good as we do not want some of those functions to be static members of classes that inherit from `DynamicObj`.
